services:
  - type: web
    name: streamlit-app
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "streamlit run aplicacion.py --server.port=10000 --server.address=0.0.0.0"